/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorDirectorio;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author JHON FAREZ
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    private ControladorDirectorio controladorDirectorio;
    private String rutaAbsoluta;
    private String rutaRelativa;
    private String carpetaActual;

    public VentanaPrincipal() {
        controladorDirectorio = new ControladorDirectorio();
        initComponents();
        this.setLocationRelativeTo(null);
        rutaAbsoluta = new String();
        rutaRelativa = new String();
        carpetaActual = new String();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        txtRuta = new javax.swing.JTextField();
        btnListarDirectorios = new javax.swing.JButton();
        btnListarArchivosOcultos = new javax.swing.JButton();
        btnListarDirectoriosOcultos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listarTodo = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaInformacion = new javax.swing.JTextArea();
        btnAtras = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuItemCrear = new javax.swing.JMenuItem();
        menuItemEliminar = new javax.swing.JMenuItem();
        menuItemRenombrar = new javax.swing.JMenuItem();
        menuItemSalir = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestionar Directorios\n");

        txtRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutaActionPerformed(evt);
            }
        });

        btnListarDirectorios.setText("Listar Directorios");
        btnListarDirectorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarDirectoriosActionPerformed(evt);
            }
        });

        btnListarArchivosOcultos.setText("Listar Archivos Ocultos");

        btnListarDirectoriosOcultos.setText("Listar Directorios Ocultos");

        listarTodo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listarTodo);

        jTextAreaInformacion.setColumns(20);
        jTextAreaInformacion.setRows(5);
        jScrollPane2.setViewportView(jTextAreaInformacion);

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        jMenu2.setText("Gestionar Directorio");

        menuItemCrear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuItemCrear.setText("Crear");
        menuItemCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCrearActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemCrear);

        menuItemEliminar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menuItemEliminar.setText("Eliminar");
        menuItemEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEliminarActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemEliminar);

        menuItemRenombrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuItemRenombrar.setText("Renombrar");
        jMenu2.add(menuItemRenombrar);

        menuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.CTRL_MASK));
        menuItemSalir.setText("Salir");
        jMenu2.add(menuItemSalir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnListarDirectorios)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnListarArchivosOcultos)
                                .addGap(46, 46, 46)
                                .addComponent(btnListarDirectoriosOcultos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAtras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSiguiente)))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(184, 184, 184))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtras)
                    .addComponent(btnSiguiente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarDirectorios)
                    .addComponent(btnListarDirectoriosOcultos)
                    .addComponent(btnListarArchivosOcultos))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutaActionPerformed


    }//GEN-LAST:event_txtRutaActionPerformed

    private void btnListarDirectoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarDirectoriosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnListarDirectoriosActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        String atras = txtRuta.getText();
        if (atras.lastIndexOf(File.separator) != -1) {
            rutaRelativa = atras.substring(0, atras.lastIndexOf(File.separator));
            carpetaActual = rutaAbsoluta.substring(rutaRelativa.lastIndexOf(File.separator) + 1, rutaRelativa.length());
           // txtNombreActual.setText(carpetaActual);
            controladorDirectorio.inicializarRuta(rutaRelativa);
            String[] resultado = controladorDirectorio.getArchivos();
            listarTodo.setListData(resultado);
            txtRuta.setText(rutaRelativa);
        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        if (rutaAbsoluta.length() != rutaRelativa.length()) {
            String atras = txtRuta.getText();
            int numer = atras.length();
            String restoRuta = rutaAbsoluta.substring(numer + 1, rutaAbsoluta.length());
            System.out.println(restoRuta);

            if (restoRuta.indexOf(File.separator) != -1) {
                rutaRelativa = atras + File.separator + restoRuta.substring(0, restoRuta.indexOf(File.separator));
                carpetaActual = rutaAbsoluta.substring(rutaRelativa.lastIndexOf(File.separator) + 1, rutaRelativa.length());
                //txtNombreActual.setText(carpetaActual);
                controladorDirectorio.inicializarRuta(rutaRelativa);
                String[] resultado = controladorDirectorio.getArchivos();
                listarTodo.setListData(resultado);

                txtRuta.setText(rutaRelativa);
            } else {
                rutaRelativa = atras + File.separator + restoRuta;
                carpetaActual = rutaAbsoluta.substring(rutaRelativa.lastIndexOf(File.separator) + 1, rutaRelativa.length());
                // txtNombreActual.setText(carpetaActual);
                controladorDirectorio.inicializarRuta(rutaRelativa);
                String[] resultado = controladorDirectorio.getArchivos();
                listarTodo.setListData(resultado);

                txtRuta.setText(rutaRelativa);
            }
        } else {
            carpetaActual = rutaAbsoluta.substring(rutaAbsoluta.lastIndexOf(File.separator) + 1, rutaAbsoluta.length());
            // txtNombreActual.setText(carpetaActual);
        }

    }

    private void lstDirectorioValueChanged(javax.swing.event.ListSelectionEvent evt) {
        String nombre = controladorDirectorio.getArchivos()[evt.getLastIndex()];
        //txtNombre.setText(nombre);
        File f = new File(txtRuta.getText(), nombre);

        if (f.isDirectory()) {
            rutaAbsoluta = txtRuta.getText() + File.separator + nombre;
            txtRuta.setText(rutaAbsoluta);
            carpetaActual = rutaAbsoluta.substring(rutaAbsoluta.lastIndexOf(File.separator) + 1, rutaAbsoluta.length());
            /// txtNombreActual.setText(carpetaActual);
            System.out.println(rutaAbsoluta);
            controladorDirectorio.inicializarRuta(rutaAbsoluta);
            String[] resultado = controladorDirectorio.getArchivos();
            listarTodo.setListData(resultado);
            System.out.println(rutaAbsoluta);

        } else {
            String contenido = controladorDirectorio.leerArchivo(nombre);
            //txtTexto.setText(contenido);
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void menuItemCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCrearActionPerformed

        String nombre ;
        nombre = JOptionPane.showInputDialog("Ingrese el nombre de su directorio ");

        File file = new File(nombre);
        if (!file.exists()) {
            try {
                file.createNewFile();
                JOptionPane.showMessageDialog(null, "Directorio creado con exito");
                JOptionPane.showMessageDialog(null,"Datos del directorio creado"+
                        "\nNombre: "+file.getName()+"\nRuta aboluta:  "+file.getAbsolutePath()+
                        "\nTamanio: "+file.length());
            } catch (IOException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null,"Directorio "+file+" ya existe");
            }
        }
    }//GEN-LAST:event_menuItemCrearActionPerformed

    private void menuItemEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnListarArchivosOcultos;
    private javax.swing.JButton btnListarDirectorios;
    private javax.swing.JButton btnListarDirectoriosOcultos;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaInformacion;
    private javax.swing.JList<String> listarTodo;
    private javax.swing.JMenuItem menuItemCrear;
    private javax.swing.JMenuItem menuItemEliminar;
    private javax.swing.JMenuItem menuItemRenombrar;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables
}
